Retry requests
zalando-incubator/play-zhewbacca pull request #19
Opened 2016-11-22 11:08 UTC by raychenon

Retry failed requests in case of network / remote server failures.
https://github.com/zalando-incubator/play-zhewbacca/issues/16

**Note :** The number of attempts and backoff duration variables need to be extracted in .conf file .

2017-02-20 17:10 UTC, LappleApple commented
@raychenon Are you guys planning on merging this PR after resolving the conflict?

2017-02-20 17:22 UTC, raychenon commented on src/main/scala/org/zalando/zhewbacca/IAMClient.scala
> +    exponentialBackoff { 100.millis }
these variables ( nb attempts and backoff duration ) should be configurable in `.conf` file

2017-02-20 17:33 UTC, raychenon commented
@LappleApple , thanks for the reminder.
Conflict resolved.
We plan to merge this PR this week.

2017-02-21 11:09 UTC, dmitrykrivaltsevich requested changes

2017-02-21 11:09 UTC, dmitrykrivaltsevich commented on src/main/scala/org/zalando/zhewbacca/IAMClient.scala
> +    exponentialBackoff { 100.millis }
Could you please make then configurable?

2017-02-21 11:10 UTC, raychenon commented on src/main/scala/org/zalando/zhewbacca/IAMClient.scala
> +    exponentialBackoff { 100.millis }
I'll do it today. Is there anything else to review ?

2017-02-21 12:07 UTC, dmitrykrivaltsevich commented on src/main/scala/org/zalando/zhewbacca/IAMClient.scala
> +    exponentialBackoff { 100.millis }
Nope

2017-02-21 16:27 UTC, dmitrykrivaltsevich approved these changes

2017-02-21 21:04 UTC, merged

2017-02-21 21:06 UTC, dmitrykrivaltsevich commented
@raychenon , could you please release 0.2.2?

2017-02-21 21:12 UTC, raychenon commented
@dmitrykrivaltsevich , I will release tomorrow . My machine is at work.

2017-02-22 11:59 UTC, dmitrykrivaltsevich commented
- resolves #19

2017-02-22 12:01 UTC, dmitrykrivaltsevich commented
@raychenon , was 0.2.2 already released?